name: qtec_task_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  #for svg icon
  websafe_svg: ^2.1.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icons/

  fonts:
    - family: BalooDa2
      fonts:
        - asset: assets/fonts/BalooDa2-Regular.ttf
          weight: 400
        - asset: assets/fonts/BalooDa2-Medium.ttf
          weight: 500
        - asset: assets/fonts/BalooDa2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BalooDa2-Bold.ttf
          weight: 700
        - asset: assets/fonts/BalooDa2-ExtraBold.ttf
          weight: 800

  uses-material-design: true
